pub static WITCH: &str = r#"
                                                                                
                                                 ↑↑                                       
                                          ↗↑↑↑↑↑ ↑↑↑ ↑↑↑↑↑                                
                                       ↑↑↑↑↑    ↑↑↑↑     ↑↑↑↑↑                            
                                    ↑↑↑↑       ↑↑ ↑↑↑        ↑↑↑                          
                                  ↑↑↑          ↑↑  ↑↑          ↑↑↑↗                       
                                ↑↑↑           ↑↑    ↑↑           ↑↑↑                      
                               ↑↑↑            ↑↑    ↑↑↑            ↑↑                     
                              ↑↑             ↑↑      ↑↑             ↑↑                    
                             ↑↑             ↑↑                                            
                          ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑ ↑↑ ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑                 
                             ↑↑↑↑          ↑↑          ↑↑           ↑↑↑                   
                            ↑↑ ↑↑↑↑        ↑↑          ↑↑↑       ↑↑↑   ↑↑                 
                            ↑↑    ↑↑↑↑    ↑↑            ↑↑     ↑↑↑     ↑↑                 
                            ↑↑      ↑↑↑↑  ↑              ↑↑ ↑↑↑        ↑↑                 
                            ↑↑         ↑↑↑↑              ↑↑ ↑          ↑↑                 
                            ↑↑            ↑↑↑          ↑↑ ↑↑          ↑↑                  
                             ↑↑         ↑↑  ↑↑↑↑     ↑↑↑  ↑↑↑         ↑↑                  
                             ↑↑↑       ↑↑      ↑  ↑↑↑      ↑↑        ↑↑                   
                              ↑↑↑      ↑        ↑↑↑ ↑       ↑↑      ↑↑                    
                               ↑↑↑    ↑↑     ↑↑↑    ↑↑↑↑    ↑↑     ↑↑                     
                                 ↑↑  ↑↑   ↑↑↑↑         ↑↑↑   ↑↑  ↑↑↑                      
                                  ↑→ ↑↑ ↑↑↑              ↑↑↑↑ ↑↑ ↑                        
                                    ↑↑↑↑↑                   ↑↑↑↑                          
                                    ↑↑  ↑↑↑↑            ↑↑↑↑↑ ↑↑↑                         
                                   ↑       ↑↑↑↑↑↑↑↑↑↑↑↑↑↑        ↑                        
                                                      
                                   
        OPTIONS:
        
        ☢ help         ☢ antivirus    ☢ attack       ☢ botnet      ☢ cubes    ☢ curl   
        ☢ firewall     ☢ lookup       ☢ osint        ☢ rootkit     ☢ scanner

        

    ██╗    ██╗██╗████████╗ ██████╗██╗  ██╗         ██████╗██████╗  █████╗ ███████╗████████╗
    ██║    ██║██║╚══██╔══╝██╔════╝██║  ██║        ██╔════╝██╔══██╗██╔══██╗██╔════╝╚══██╔══╝
    ██║ █╗ ██║██║   ██║   ██║     ███████║        ██║     ██████╔╝███████║█████╗     ██║   
    ██║███╗██║██║   ██║   ██║     ██╔══██║        ██║     ██╔══██╗██╔══██║██╔══╝     ██║   
    ╚███╔███╔╝██║   ██║   ╚██████╗██║  ██║███████╗╚██████╗██║  ██║██║  ██║██║        ██║   
     ╚══╝╚══╝ ╚═╝   ╚═╝    ╚═════╝╚═╝  ╚═╝╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝        ╚═╝   

"#;


pub static NOTES: &str = r#"
WARNINGS

    WARNING: This Tool Is For Cybersecurity Use May Have Legal Implications
    As you use this cybersecurity tool, it is important to be aware of the potential 
    legal implications. Depending on how the tool is used, there may be consequences 
    under various laws and regulations.

ENVIRONMENT

    To ensure a smooth installation process, make sure your Linux system has all 
    necessary dependencies, including packages and files.    

FILES

    Attention! The 'witch_spells' folder must be located within 
    '/var/witch_craft/witch_spells' directory,    and the current user must have 
    read/write permissions to access it. Failure to meet these requirements may 
    result in unexpected behavior or errors during the cleaning process. 

                    automatically generated by witch_craft®
"#;